### PR TITLE
Add additional tags to instances being launched

### PR DESCRIPTION
**Pull request by kchugalinskiy**
At this moment there is a lack of instance tags on elk instances. This may be extremely useful for cost estimation and categorization of ELK cluster.

This PR provides a solution, adding optional `tags` variable, which is exposed to all resources: directly (sg, iam) and idirectly (asg).

### CODE REVIEW

**Comment by kostyrev** [comment]
Kostya, you should respect current indentation

**Comment by kchugalinskiy** [comment]
@kostyrev if it works for you, I would prefer to fix all indentation in separate PR, as it is completely out of terraform guidelines. It doesn't pass `terraform fmt`

**Comment by kostyrev** [comment]
that's what I meant

**Comment by kchugalinskiy** [comment]
@kostyrev I've removed all extra indentation

**Comment by kchugalinskiy** [comment]
@kostyrev any updates here?

**Pull request merged**
